# permissions for end users to view deploysets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deployset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deployment-operator
    app.kubernetes.io/part-of: deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: deployset-viewer-role
rules:
- apiGroups:
  - deploy.nagesh-node.me
  resources:
  - deploysets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.nagesh-node.me
  resources:
  - deploysets/status
  verbs:
  - get
