---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - deploy.nagesh-node.me
  resources:
  - deploysets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.nagesh-node.me
  resources:
  - deploysets/finalizers
  verbs:
  - update
- apiGroups:
  - deploy.nagesh-node.me
  resources:
  - deploysets/status
  verbs:
  - get
  - patch
  - update
